spring.application.name=socios
server.port=${PORT:8082}
# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (NEON / POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-lucky-night-ap8zx1yg-pooler.c-7.us-east-1.aws.neon.tech/neondb?
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Sx7qLrmA9FbM
spring.datasource.driver-class-name=org.postgresql.Driver



# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# Esto hace que Spring cree o actualice las tablas automáticamente en la base de datos
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SHOW_SQL:true}
