spring.application.name=socios

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (NEON / POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://[AQUI_TU_URL_DE_NEON]/neondb?sslmode=require
spring.datasource.username=[user]
spring.datasource.password=[contra]
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# Esto hace que Spring cree o actualice las tablas automáticamente en la base de datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true